#version 450


layout(local_size_x = 32, local_size_y = 32) in;
layout(binding = 0, rgba8) uniform image2D inImage;
layout(binding = 1) buffer outValue
{
  uint minmax[2];
};


void main()
{
  vec4 fragColor = imageLoad(inImage, ivec2(gl_GlobalInvocationID.xy));

  if(fragColor.z > 0)
  {

    atomicMin(minmax[0], floatBitsToInt(fragColor.z));
    atomicMax(minmax[1], floatBitsToInt(fragColor.z));
  }
}
